server:
  port: 8093

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    protocol: smtp
    username: disparador.teste@gmail.com
    password: qbzuntikbzwltvzb
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          quitwait: false

  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin